### PR TITLE
Improve build and install docs

### PR DESCRIPTION
**Pull request by EliRibble**
Some of the instructions were wrong, some of them could just be clearer. This is based on my experience building on Ubuntu 16.04 LTS today.

### CODE REVIEW

**Comment by nallath** [comment]
I've build protobuff with cmake. As we use cmake for all our build systems, we also use it for protobuf. 

Is there a specific reason this didn't work for you?

**Comment by EliRibble** [comment]
You can build with cmake, but you don’t have to. protobuf documentation:

https://github.com/google/protobuf/blob/master/src/README.md

cmake is only mentioned when building on windows. Otherwise it’s a pretty standard autopen/configure/make setup.

**Comment by Ghostkeeper** [comment]
I'm agreeing with Nallath. CMake works fine and it's the same was as all of our other dependencies are built too. Keeping the process more or less the same on Linux, OSX and Windows is also a plus in my book.

But it doesn't hurt to document them both. Perhaps the autogen method can be documented as an alternative instead of replacing the CMake documentation?

**Comment by Ghostkeeper** [comment]
Devs, see CURA-4019.

**Comment by EliRibble** [comment]
Okay, I can see your point about consistency, but you're essentially handing out false information because the instructions you supply do not match with the instructions provided by the protobuf project itself. If nothing else, change your instructions to a link to protobuf's build instructions so that people have the most accurate information on how to build it

**Comment by EliRibble** [comment]
My last comment was a bit harsh, sorry. I'm not a fan of cmake, especially having to use the cmakegui, but that shouldn't color this conversation.

At this point I've contributed all I'm going to. I don't want to influence your process further. I thought this was a simple documentation bug I could help with, but since it's an active decision it probably makes sense to just decline my PR.

**Comment by awhiemstra** [comment]
The protobuf build stuff should not be in this repository in the first place. We originally had that because it was hard to get packages for Protobuf 3. Since most distributions now ship it I have removed the build instructions for Protobuf.

**Comment by bburket** [comment]
So @awhiemstra I am having building as well. 
```
CMake Error at /usr/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR) (Required is at
  least version "3.0.0")
```

I tried install protocol buffers from google's build instructions (it was absolutely not part of the Ubuntu 17.10 distro) and it seems somewhat successful: 
```
bill@billbuntu:~/code/libArcus/build$ protoc --version
libprotoc 3.4.0
```

What am I missing here?

**Comment by Ghostkeeper** [comment]
You'd need the `dev` version of Protobuf, in order to include its header files.

**Pull request closed without merging**
