### PR TITLE
Fix the RPATH value.

### PR DESCRIPTION
**Pull request by krop**
CMAKE_INSTALL_RPATH should not be hardcoded but point to the library install
path.

### CODE REVIEW

**Comment by krop** [comment]
From the error, looks like the Windows CI compiler and the one used to build protobuf disagree about which c++ abi they support.

**Comment by nallath** [comment]
@awhiemstra; Could you have a look at this?

**Comment by krop** [comment]
ping ? noone to review ?

**Comment by Ghostkeeper** [comment]
It seems to work. It also still respects the `CMAKE_INSTALL_PREFIX` user preference from what I can tell. Thank you for the fix.

**Pull request merged**
