### PR TITLE
[master] Revert "Do not use GNUInstallDirs but hardcode lib as library directory"

### PR DESCRIPTION
**Pull request by thopiekar**
This reverts commit 6eeb6748f2b31fd2ff3edf9698708df9d2d477fc.

Same as #21

### CODE REVIEW

**Comment by thopiekar** [comment]
Tested with cura-build:

```
thopiekar@home:[...]/Ultimaker/cura-build$ git diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index dddf48c..da15c4a 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -367,8 +367,8 @@ endif()
 
 ExternalProject_Add(Arcus
     DEPENDS Python Protobuf Sip
-    GIT_REPOSITORY https://github.com/ultimaker/libArcus
-    GIT_TAG origin/${TAG_OR_BRANCH}
+    GIT_REPOSITORY https://github.com/thopiekar/libArcus
+    GIT_TAG origin/master-GNUInstallDirs-revert
     CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${EXTERNALPROJECT_INSTALL_PREFIX} -DBUILD_EXAMPLES=OFF -DBUILD_STATIC=ON -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ${ARCUS_EXTRA_ARGS}
 )
```

```
[ 15%] Completed 'Sip'
[ 15%] Built target Sip
Scanning dependencies of target Arcus
[ 16%] Creating directories for 'Arcus'
[ 17%] Performing download step (git clone) for 'Arcus'
Klone nach 'Arcus' ...
Note: checking out 'origin/master-GNUInstallDirs-revert'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD ist jetzt bei 1bdbe5a... Revert "Do not use GNUInstallDirs but hardcode lib as library directory"
[ 18%] No patch step for 'Arcus'
[ 19%] Performing update step for 'Arcus'
Aktueller Branch HEAD ist auf dem neuesten Stand.
[ 20%] Performing configure step for 'Arcus'
-- The C compiler identification is GNU 5.3.1
-- The CXX compiler identification is GNU 5.3.1
-- Check for working C compiler: /usr/lib/icecc/bin/cc
-- Check for working C compiler: /usr/lib/icecc/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib/icecc/bin/c++
-- Check for working CXX compiler: /usr/lib/icecc/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found PROTOBUF: /usr/lib/x86_64-linux-gnu/libprotobuf.so  
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.5.1", minimum required is "3.4.0") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so (found suitable version "3.5.1+", minimum required is "3.4.0") 
-- Found SIP version: 4.17
-- Configuring done
-- Generating done
-- Build files have been written to: [...]/Ultimaker/cura-build/build/Arcus-prefix/src/Arcus-build
[ 21%] Performing build step for 'Arcus'
Scanning dependencies of target Arcus
[  6%] Building CXX object CMakeFiles/Arcus.dir/src/Socket.cpp.o
[ 13%] Building CXX object CMakeFiles/Arcus.dir/src/SocketListener.cpp.o
[ 20%] Building CXX object CMakeFiles/Arcus.dir/src/MessageTypeStore.cpp.o
[ 26%] Building CXX object CMakeFiles/Arcus.dir/src/PlatformSocket.cpp.o
[ 33%] Building CXX object CMakeFiles/Arcus.dir/src/Error.cpp.o
Linking CXX static library libArcus.a
[ 33%] Built target Arcus
[ 40%] Generating python/sipArcuspart0.cpp, python/sipArcuspart1.cpp, python/sipArcuspart2.cpp, python/sipArcuspart3.cpp, python/sipArcuspart4.cpp, python/sipArcuspart5.cpp, python/sipArcuspart6.cpp, python/sipArcuspart7.cpp

Scanning dependencies of target python_module_Arcus
[ 46%] Building CXX object CMakeFiles/python_module_Arcus.dir/python/sipArcuspart0.cpp.o
[ 53%] Building CXX object CMakeFiles/python_module_Arcus.dir/python/sipArcuspart1.cpp.o
[ 60%] Building CXX object CMakeFiles/python_module_Arcus.dir/python/sipArcuspart2.cpp.o
[ 66%] Building CXX object CMakeFiles/python_module_Arcus.dir/python/sipArcuspart3.cpp.o
[ 73%] Building CXX object CMakeFiles/python_module_Arcus.dir/python/sipArcuspart4.cpp.o
[ 80%] Building CXX object CMakeFiles/python_module_Arcus.dir/python/sipArcuspart5.cpp.o
[ 86%] Building CXX object CMakeFiles/python_module_Arcus.dir/python/sipArcuspart6.cpp.o
[ 93%] Building CXX object CMakeFiles/python_module_Arcus.dir/python/sipArcuspart7.cpp.o
[100%] Building CXX object CMakeFiles/python_module_Arcus.dir/python/PythonMessage.cpp.o
Linking CXX shared library Arcus.so
[100%] Built target python_module_Arcus
[ 22%] Performing install step for 'Arcus'
[ 33%] Built target Arcus
[100%] Built target python_module_Arcus
Install the project...
-- Install configuration: ""
-- Installing: [...]/Ultimaker/cura-build/build/inst/lib/python3/dist-packages/Arcus.so
-- Set runtime path of "[...]/Ultimaker/cura-build/build/inst/lib/python3/dist-packages/Arcus.so" to "[...]/Ultimaker/cura-build/build/inst/lib"
-- Installing: [...]/Ultimaker/cura-build/build/inst/lib/libArcus.a
-- Installing: [...]/Ultimaker/cura-build/build/inst/include/Arcus/Socket.h
-- Installing: [...]/Ultimaker/cura-build/build/inst/include/Arcus/SocketListener.h
-- Installing: [...]/Ultimaker/cura-build/build/inst/include/Arcus/Types.h
-- Installing: [...]/Ultimaker/cura-build/build/inst/include/Arcus/ArcusExport.h
-- Installing: [...]/Ultimaker/cura-build/build/inst/include/Arcus/MessageTypeStore.h
-- Installing: [...]/Ultimaker/cura-build/build/inst/include/Arcus/Error.h
-- Installing: [...]/Ultimaker/cura-build/build/inst/lib/cmake/Arcus/Arcus-targets.cmake
-- Installing: [...]/Ultimaker/cura-build/build/inst/lib/cmake/Arcus/Arcus-targets-noconfig.cmake
-- Installing: [...]/Ultimaker/cura-build/build/inst/lib/cmake/Arcus/ArcusConfig.cmake
-- Installing: [...]/Ultimaker/cura-build/build/inst/lib/cmake/Arcus/ArcusConfigVersion.cmake
[ 22%] Completed 'Arcus'
[ 22%] Built target Arcus
Scanning dependencies of target CuraEngine
```

**Comment by thopiekar** [comment]
@awhiemstra @Ghostkeeper Could you take another look on this? This is a very old issue and really doesn't make it possible to install ```libArcus``` properly outside ```cura-build```.

**Comment by Ghostkeeper** [comment]
I'd consider not hardcoding them better from a programming standpoint, but the original issue why it was hardcoded is hocus pocus for me so I'd rather leave this for awhiemstra to decide.

**Comment by thopiekar** [comment]
Maybe there was a good reason for this in the past, but I reverted this change and ran cura-build with it and now it still works. So whatever it was that caused the problem in the past, it has already been fixed (in cura-build). So this hardcoding is not needed anymore...

**Comment by nallath** [comment]
Less hardcodes is always better :)

**Comment by Ghostkeeper** [comment]
Well unless "GNUInstallDirs is silly and uses incorrect dirs on certain platforms" :wink:

**Comment by thopiekar** [comment]
I guess it is always possible to force cmake to use a specific value for a
variable. Additionally that says nothing. "Certain platforms" could also be
FreeBSD or anything else. It would be helpful to know which platforms
really have problems here.
If it is OSX or Windows I would even invest some time to get it fixed
there...

This PR is hurting me more than any other problem with Cura (and etc) here.

**Comment by awhiemstra** [comment]
The original reason for changing it is that GNUInstallDirs makes certain bad assumptions. Specifically, on my Arch machine it will insist on installing libraries into a lib64 dir, whereas it should just use lib. Admittedly that should probably be filed as an upstream bug.

**Comment by thopiekar** [comment]
Ah, ok. So the default on Arch is lib64. Maybe we can add a check for this somewhere.
Btw., what is the name of the directory where 32bit libraries go in? ```lib32```?

**Comment by awhiemstra** [comment]
There actually is an upstream bug for it: https://public.kitware.com/Bug/view.php?id=15373

32-bit stuff goes to lib32 on a 64-bit system, whereas on a 32-bit it goes to /lib. Effectively, on Arch, lib contains the native architecture stuff, whereas other architectures end up in architecture specific dirs.

**Comment by thopiekar** [comment]
I wouldn't call it a "bug". It is actually Arch's design of saving libraries. I would prefer to add in cura-build a override on CMAKE_LIB_DIR (or however it is called correctly).

**Comment by thopiekar** [comment]
I just added a PR which forces to use "lib" as LIBDIR. Could you take a look on it, so we can apply this here?

Thanks

**Comment by Ghostkeeper** [comment]
https://github.com/Ultimaker/cura-build/pull/55

**Comment by thopiekar** [comment]
Can we merge these things? :wink:

**Comment by thopiekar** [comment]
@awhiemstra Ping

**Comment by awhiemstra** [comment]
I will merge this, but we should make sure that cura-build keeps using the existing directories, but I will discuss that in the other PR.

**Comment by thopiekar** [comment]
Thanks

**Pull request merged**
