### PR TITLE
[2.1] Revert "Do not use GNUInstallDirs but hardcode lib as library directory"

### PR DESCRIPTION
**Pull request by thopiekar**
This reverts commit 6eeb6748f2b31fd2ff3edf9698708df9d2d477fc.

### CODE REVIEW

**Comment by awhiemstra** [comment]
Hi thopiekar,

Any chance you can rebase this on master and update the PR? We can merge it after that.

**Comment by thopiekar** [comment]
Yes, of course.

**Comment by thopiekar** [comment]
@awhiemstra , done. Any JIRA issue where my PR is needed?

Additionally, how does it come that this PR is still needed? I thought 2.1 has been freezed.

**Comment by Ghostkeeper** [comment]
2.1 is frozen, which is why this should be rebased on master.

**Comment by thopiekar** [comment]
Already merged into master 😉

It was just splitted into two commits. One for master and for 2.1

Mit freundlichen Grüßen/With kind regards
- Thomas Karl Pietrowski

**Pull request closed without merging**
