### PR TITLE
Don't link to libpython for Python >= 3.8

### PR DESCRIPTION
**Pull request by gferon**
As of Python 3.8, python C extensions modules should not link to
libpython, unless they embed the interpreter in their code.

Relevant upstream PR: https://github.com/python/cpython/pull/12946

Signed-off-by: Gabriel Féron <feron.gabriel@gmail.com>

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
It looks also like this won't be possible on Windows, according to that PR and the [changelog of Python](https://docs.python.org/3/whatsnew/3.8.html#debug-build-uses-the-same-abi-as-release-build). So this only applies to Linux then.

I'm using Python 3.8 in my development environment and linking to CPython works just fine. I understand that this makes it easier to create a build script, but with the build script already set up does it have any tangible advantage?

**Comment by hroncok** [comment]
> I'm using Python 3.8 in my development environment and linking to CPython works just fine.

Yes, linking works fine. So does not linking. Not linking makes it possible to import the module from a debug build of Python. Linking gives no advantages. So:

Linking to libpython:

 - works
 - can be safely done everyhwhere
 - the module can only be imported in Python linked against the same libpython

Not linking to libpython:

 - works (on Python 3.8+ on Unix)
 - needs "logic" to determine whether to link (or using `python-config  --libs`)
 - the module can be imported into Python linked against a different libpython (e.g. the debug build)


> I understand that this makes it easier to create a build script...

I don't understand this part. What build script?

**Comment by Ghostkeeper** [comment]
> I don't understand this part. What build script?

I meant the CMake scripts, such as the modified file: https://github.com/Ultimaker/libArcus/blob/master/cmake/SIPMacros.cmake . I guess technically that would be a "configure" script to the maintainers, sorry :smiley: You wouldn't need to find the Python libraries, and then wouldn't need to write that `TARGET_LINK_LIBRARIES` command.
Since Python 3.8 the debug build is also binary compatible with the release build. I get what you mean though. That is the tangible benefit I was asking for.

**Comment by krop** [comment]
This commit breaks the build when using '-Wl,--as-needed'

**Comment by hroncok** [comment]
Breaks how?

**Comment by krop** [comment]
The comment above was edited.

**Comment by hroncok** [comment]
Well it does "break" it indeed, but only because you say "every reference needs to be defined" which is not true for Python extension modules. What is the purpose for using `-Wl,--no-undefined`?

**Comment by Ghostkeeper** [comment]
Heh, gave me quite a headache but found an issue with this code. I made an adjustment here to allow our build server to run it again: https://github.com/Ultimaker/libArcus/commit/b6c89c7de172accd10c97eb81384320137b1be74

See the commit message for the reasoning. We had temporarily reverted these changes a week ago because of that build issue. It should be fixed more properly now (build pending). Please see if it still works for you as well.

**Comment by StefanBruens** [comment]
> Well it does "break" it indeed, but only because you say "every reference needs to be defined" which is not true for Python extension modules. What is the purpose for using `-Wl,--no-undefined`?

It is the correct flag for `libArcus.so` - you don't want undefined symbols in a regular shared library. Using it turns a potential runtime error into a build time error.

For the python module `Arcus.so` there will be undefined symbols. The fault lies with the `add_sip_python_module` macro, which uses the correct `MODULE` library type only on Cygwin or for APPLE, and uses `SHARED` otherwise. `MODULE` and `SHARED` have distinct `CMAKE_{MODULE,SHARED}_LINKER_FLAGS`, and using `MODULE` for the python module allows to keep `--no-undefined` for the regular (`SHARED`) library.

**Pull request merged**
